[package]
name = "glushkovizer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfgrammar = "0.13.4"
dot = "0.1.4"
lrlex = "0.13.4"
lrpar = "0.13.4"

[build-dependencies]
cfgrammar = "0.13.4"
lrlex = "0.13.4"
